"""
Extract TIPS-2024 partition function data from pickle files and write
a Julia source file with embedded Q(T) tables for atmospheric molecules.

Reference: Gamache et al. 2025, JQSRT 345, 109568.
"""

import os
import pickle
import numpy as np

DATA_DIR = os.path.join(os.path.dirname(__file__),
                        '../data/tips/TIPS_2024_v1p2_py/data')
OUT_FILE = os.path.join(os.path.dirname(__file__),
                        '../src/HITRAN/tips2024_data.jl')

# Temperature range to extract (K). Covers full atmospheric range
# with margin; 1K integer steps (native resolution of the TIPS tables).
T_MIN = 70
T_MAX = 400

# Molecules to extract: mol_id -> list of iso_ids (1-based, strings in the file).
# Matches the molecules in partition.jl and fetch.jl.
MOLECULES = {
    1:  list(range(1, 7)),   # H2O  iso 1-6
    2:  list(range(1, 14)),  # CO2  iso 1-13
    3:  list(range(1, 6)),   # O3   iso 1-5
    4:  list(range(1, 6)),   # N2O  iso 1-5
    5:  list(range(1, 7)),   # CO   iso 1-6
    6:  list(range(1, 5)),   # CH4  iso 1-4
    7:  list(range(1, 4)),   # O2   iso 1-3
    9:  list(range(1, 3)),   # SO2  iso 1-2
    11: list(range(1, 3)),   # NH3  iso 1-2
}

MOL_NAMES = {
    1: "H2O", 2: "CO2", 3: "O3", 4: "N2O", 5: "CO",
    6: "CH4", 7: "O2", 9: "SO2", 11: "NH3",
}

def load_qtdict(mol_id):
    path = os.path.join(DATA_DIR, f'{mol_id}.QTpy')
    with open(path, 'rb') as f:
        return pickle.loads(f.read())

def extract(mol_id, iso_ids, qtdict):
    """Return dict iso_id -> list of Q values for T in T_MIN..T_MAX."""
    result = {}
    for iso_id in iso_ids:
        key = str(iso_id)
        if key not in qtdict:
            print(f"  WARNING: mol_id={mol_id} iso_id={iso_id} not in QTpy, skipping")
            continue
        iso_data = qtdict[key]
        temps = list(range(T_MIN, T_MAX + 1))
        available = [t for t in temps if t in iso_data]
        if len(available) != len(temps):
            missing = [t for t in temps if t not in iso_data]
            print(f"  WARNING: mol_id={mol_id} iso_id={iso_id} missing T={missing[:5]}...")
            if not available:
                continue
        vals = [float(iso_data[t]) for t in available]
        if len(available) != len(temps):
            # Store only available range
            result[iso_id] = (available[0], available[-1], vals)
        else:
            result[iso_id] = (T_MIN, T_MAX, vals)
    return result

def format_vector(vals):
    """Format a list of floats as a Julia Float64 vector literal."""
    chunks = []
    line = "        ["
    for i, v in enumerate(vals):
        token = f"{v:.6g}"
        if i < len(vals) - 1:
            token += ","
        # Wrap at ~100 chars
        if len(line) + len(token) + 1 > 100:
            chunks.append(line)
            line = "         " + token
        else:
            if i == 0:
                line += token
            else:
                line += " " + token
    line += "]"
    chunks.append(line)
    return "\n".join(chunks)

def main():
    lines = []
    lines.append('# Auto-generated by scripts/extract_tips.py — do not edit manually.')
    lines.append('# Source: TIPS-2024 v1.2 (Gamache et al. 2025, JQSRT 345, 109568)')
    lines.append('#')
    lines.append(f'# Q(T) tables for T = {T_MIN}:{T_MAX} K (1 K steps).')
    lines.append('# Key: (mol_id, iso_id) => Vector{Float64} of Q values.')
    lines.append('# Use linear interpolation between integer T points.')
    lines.append('')
    lines.append(f'const TIPS_T_MIN = {T_MIN}')
    lines.append(f'const TIPS_T_MAX = {T_MAX}')
    lines.append('')
    lines.append('const TIPS2024_DATA = Dict{Tuple{Int,Int}, Vector{Float64}}(')

    entries = []
    for mol_id, iso_ids in sorted(MOLECULES.items()):
        name = MOL_NAMES[mol_id]
        print(f"Processing {name} (mol_id={mol_id})...")
        qtdict = load_qtdict(mol_id)
        data = extract(mol_id, iso_ids, qtdict)
        for iso_id, (t_lo, t_hi, vals) in sorted(data.items()):
            if t_lo != T_MIN or t_hi != T_MAX:
                comment = f"    # {name} iso {iso_id} (T={t_lo}–{t_hi} K)"
            else:
                comment = f"    # {name} iso {iso_id}"
            vec = format_vector(vals)
            entries.append(f"{comment}\n    ({mol_id}, {iso_id}) => {vec.strip()}")

    lines.append(",\n".join(entries))
    lines.append(')')
    lines.append('')

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    with open(OUT_FILE, 'w') as f:
        f.write('\n'.join(lines))

    print(f"\nWrote {OUT_FILE}")
    print(f"  {len(entries)} isotopologues, T = {T_MIN}–{T_MAX} K")

if __name__ == '__main__':
    main()
